-- ========================================================================================
-- Central Collaboration Hub - Phase 4: Storage Setup
-- ========================================================================================

-- 1. Create the 'documents' bucket (Private bucket)
insert into storage.buckets (id, name, public) 
values ('documents', 'documents', false) 
on conflict (id) do nothing;

-- 2. Storage Policies
-- Allow authenticated users to upload files to the 'documents' bucket
create policy "Authenticated users can upload documents"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'documents' );

-- Allow users to update their own uploaded files
create policy "Users can update their own documents"
  on storage.objects for update
  to authenticated
  using ( bucket_id = 'documents' and owner = auth.uid() );

-- Allow users to read files (Note: In our app, we will primarily use 
-- Pre-Signed URLs generated by the client after verifying access in the `files` table, 
-- but this allows basic read access for the owner).
create policy "Users can view their own documents"
  on storage.objects for select
  to authenticated
  using ( bucket_id = 'documents' and owner = auth.uid() );

create policy "Users can delete their own documents"
  on storage.objects for delete
  to authenticated
  using ( bucket_id = 'documents' and owner = auth.uid() );
